config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get 'home/index'
  get 'home/about'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    #added new fieldname and allowing rails to accept it from a webfrom
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) 
        devise_parameter_sanitizer.permit(:account_update, keys: [:name]) 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show] # all users can view pins
  before_action :correct_user, only: [:edit, :update, :destroy] # only the user that created a specific pin can alter that pin

  # GET /pins or /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)  #objects are pulled from database then shown fron newest to oldest
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:description, :image, :name) # allow images 
    end

   def correct_user                                    #checks for the correct user 
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<!--navbar-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%=link_to 'Pinterested',root_path, class:'navbar-brand' %>     
         <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#"><span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#"></a>
        </li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path, class:"btn btn-default" %></li>
        <li><%= link_to 'About', home_about_path, class:"btn btn-default" %></li>
        <li><%= link_to 'List Pins', pins_path, class:"btn btn-default" %></li>
     
       <!-- options based on whether a user is logged in or not -->
       <!-- If logged in, then the provided options are to edit profile or logout  -->

       <% if user_signed_in? %>

            <li><%= link_to 'Edit Profile', edit_user_registration_path, class:"btn btn-default"  %></li>
            <li><%= link_to 'Add Pin', new_pin_path, class:"btn btn-default" %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"btn btn-default"  %></li>

      <% else %>
          <!-- If not logged in, then the provided options are to sign up or login  -->

            <li><%= link_to 'Login', new_user_session_path, class:"btn btn-default"  %></li>
            <li><%= link_to 'Join', new_user_registration_path, class:"btn btn-default"  %></li>

       <% end %>
     
               
     
      </ul>
     
     
    </div>
  </nav>

app/views/home/index.html.erb
<div class="jumbotron" style="background-color: #44272e;">
<h1 style="color:orange;">Home#index</h1>
<p style="color:orange;">Find me in app/views/home/index.html.erb</p>
<%= link_to 'Home', root_path, class:"btn btn-primary" %>
<%= link_to 'About', home_about_path, class:"btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterested</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1"> <!--makes site mobile friendly-->

    <!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    
  </head>

  <body>
    <%= render 'home/header' %> <!--place navbar on each page-->

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
    <%= yield %>
    </div>
    </body>
    <footer> 
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
     
                
  </footer>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, multipart: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
      </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<!-- wrapped the entire page in a div and each pin in a div -->
<div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
      <div class="box">
        <div class="panel panel-default">
          <%= link_to image_tag(pin.image), pin %><br/>
        <div class="panel-body">
          <%= pin.description %><br/>
          <strong><%= pin.user.name if pin.user %></strong><br>
        </div>
        <div class="panel-footer">
          <% if pin.user == current_user %>        <!-- if this this the authenticated user -->
            <%= link_to 'Edit', edit_pin_path(pin) %><br/>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>          
          <% end %>
        </div>
      
        <% end %>
 <br>
<%= link_to 'New Pin', new_pin_path %>
      </div>
    </div>  
</div>


<div class="center">
<%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
 <div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel-heading center">
      <div class="panel-heading center"><%= image_tag(@pin.image) %></div>
        <div class="panel-body">
            <%= @pin.description %><br/>
            <br/><%= @pin.user.name %><br/>

  

            <% if @pin.user == current_user %>  <!-- if the user is the same user that created the pin-->
                <%= link_to 'Edit', edit_pin_path(@pin) %> |
            <% end %>
            <%= link_to 'Back', pins_path %>
        </div>
    </div>
  </div>
</div>

      